name: Artifacts

on: [workflow_dispatch]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: carramba-woo-order-tracking
          path: |
            assets/
            includes/
            templates/
            ./*.php
