name: Artifacts

on: [workflow_dispatch]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            assets
            includes
            README.md
            uninstall.php
            !.gitignore
